services:
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: moono-kafka
    ports:
      - "9092:9092"
    environment:
      # 1. KRaft 모드 활성화 (Zookeeper 없이 동작)
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

      # 3. 리스너 설정
      KAFKA_LISTENERS: 'DOCKER://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093'
      KAFKA_ADVERTISED_LISTENERS: 'DOCKER://kafka:29092,EXTERNAL://${EC2_PUBLIC_IP:-localhost}:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'DOCKER:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'DOCKER'

      # 4. 성능 및 안정성 설정
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - moono-network

  redis:
    image: redis:latest
    container_name: moono-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - moono-network

volumes:
  kafka-data:
  redis-data:

networks:
  moono-network:
    name: moono-network