services:
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: moono-kafka
    ports:
      - "9092:9092"
    environment:
      # 1. KRaft 모드 활성화 (Zookeeper 없이 동작)
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

      # 3. 리스너 설정
      KAFKA_LISTENERS: 'DOCKER://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093'
      KAFKA_ADVERTISED_LISTENERS: 'DOCKER://kafka:29092,EXTERNAL://${EC2_PUBLIC_IP:-localhost}:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'DOCKER:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'DOCKER'

      # 4. 성능 및 안정성 설정
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      # 토픽 생성 시 기본 파티션 개수 설정
      KAFKA_NUM_PARTITIONS: 3 

    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - moono-network

  redis:
    image: redis:latest
    container_name: moono-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - moono-network
      
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: moono-kafka-ui
    ports:
      - "8989:8080"
    environment:
      # KRaft 모드에서는 ZOOKEEPER 설정 대신 BOOTSTRAPSERVERS만 필요합니다.
      - KAFKA_CLUSTERS_0_NAME=moono-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_METRICS_PORT=9997
      - DYNAMIC_CONFIG_ENABLED=true
    depends_on:
      - kafka
    networks:
      - moono-network

  kafka-exporter:
    image: danielqsj/kafka-exporter:latest
    container_name: moono-kafka-exporter
    command:
      - --kafka.server=kafka:29092
    ports:
      - "9308:9308"
    networks:
      - moono-network
    restart: always
    depends_on:
      - kafka

volumes:
  kafka-data:
  redis-data:

networks:
  moono-network:
    name: moono-network